src/Entity/Viajero.php
<?php

namespace App\Entity;

use App\Repository\ViajeroRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use PHPUnit\Framework\TestCase;

/**
* @ORM\Entity(repositoryClass=ViajeroRepository::class)
*/
class Viajero
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cedula;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_nacimiento;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telefono;

    /**
     * @ORM\OneToMany(targetEntity=ListViajes::class, mappedBy="Viajero")
     */
    private $listViajes;

    /**
     * @ORM\ManyToOne(targetEntity=RegistroViajes::class, inversedBy="viajeros")
     * @ORM\JoinColumn(nullable=false)
     */
    private $registroviajes;

    public function __construct()
    {
        $this->listViajes = new ArrayCollection();
    }

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCedula(): ?string
    {
        return $this->cedula;
    }

    public function setCedula(string $cedula): self
    {
        $this->cedula = $cedula;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(\DateTimeInterface $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    /**
     * @return Collection<int, ListViajes>
     */
    public function getListViajes(): Collection
    {
        return $this->listViajes;
    }

    public function addListViaje(ListViajes $listViaje): self
    {
        if (!$this->listViajes->contains($listViaje)) {
            $this->listViajes[] = $listViaje;
            $listViaje->setViajero($this);
        }

        return $this;
    }

    public function removeListViaje(ListViajes $listViaje): self
    {
        if ($this->listViajes->removeElement($listViaje)) {
            // set the owning side to null (unless already changed)
            if ($listViaje->getViajero() === $this) {
                $listViaje->setViajero(null);
            }
        }

        return $this;
    }

    public function getRegistroviajes(): ?RegistroViajes
    {
        return $this->registroviajes;
    }

    public function setRegistroviajes(?RegistroViajes $registroviajes): self
    {
        $this->registroviajes = $registroviajes;

        return $this;
    }

}

src/Form/ViajeroType.php
<?php

namespace App\Form;

use App\Entity\Viajero;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ViajeroType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('cedula')
            ->add('nombre')
            ->add('fecha_nacimiento')
            ->add('telefono')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Viajero::class,
        ]);
    }
}

src/Controller/ViajeroController.php
<?php

namespace App\Controller;

use App\Entity\Viajero;
use App\Form\ViajeroType;
use App\Repository\ViajeroRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class ViajeroController extends AbstractController
{
    /**
     * @Route("/", name="app_viajero_index", methods={"GET"})
     */
    public function index(ViajeroRepository $viajeroRepository): Response
    {
        return $this->render('viajero/index.html.twig', [
            'viajeros' => $viajeroRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_viajero_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ViajeroRepository $viajeroRepository): Response
    {
        $viajero = new Viajero();
        $form = $this->createForm(ViajeroType::class, $viajero);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $viajeroRepository->add($viajero, true);

            return $this->redirectToRoute('app_viajero_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('viajero/new.html.twig', [
            'viajero' => $viajero,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_viajero_show", methods={"GET"})
     */
    public function show(Viajero $viajero): Response
    {
        return $this->render('viajero/show.html.twig', [
            'viajero' => $viajero,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_viajero_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Viajero $viajero, ViajeroRepository $viajeroRepository): Response
    {
        $form = $this->createForm(ViajeroType::class, $viajero);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $viajeroRepository->add($viajero, true);

            return $this->redirectToRoute('app_viajero_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('viajero/edit.html.twig', [
            'viajero' => $viajero,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_viajero_delete", methods={"POST"})
     */
    public function delete(Request $request, Viajero $viajero, ViajeroRepository $viajeroRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$viajero->getId(), $request->request->get('_token'))) {
            $viajeroRepository->remove($viajero, true);
        }

        return $this->redirectToRoute('app_viajero_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/viajero/_delete_form.html.twig
<form method="post" action="{{ path('app_viajero_delete', {'id': viajero.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ viajero.id) }}">
    <button class="btn">Delete</button>
</form>

templates/viajero/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/viajero/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Viajero{% endblock %}

{% block body %}
    <h1>Edit Viajero</h1>

    {{ include('viajero/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_viajero_index') }}">back to list</a>

    {{ include('viajero/_delete_form.html.twig') }}
{% endblock %}

templates/viajero/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Viajero index{% endblock %}

{% block body %}

    

    <div class="conatiner w-75 ms-5">
        <h1>Viajero index</h1>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cedula</th>
                <th>Nombre</th>
                <th>Fecha_nacimiento</th>
                <th>Telefono</th>
                <th class="ps-5">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for viajero in viajeros %}
            <tr>
                <td>{{ viajero.id }}</td>
                <td>{{ viajero.cedula }}</td>
                <td>{{ viajero.nombre }}</td>
                <td>{{ viajero.fechaNacimiento ? viajero.fechaNacimiento|date('Y-m-d') : '' }}</td>
                <td>{{ viajero.telefono }}</td>
                <td>
                    <a href="{{ path('app_viajero_show', {'id': viajero.id}) }}" class="px-5">Ver</a>
                    <a href="{{ path('app_viajero_edit', {'id': viajero.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Registro No Encontrado</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_viajero_new') }}">Nuevo</a>
</div>
{% endblock %}

templates/viajero/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Viajero{% endblock %}

{% block body %}
    <h1>Create new Viajero</h1>

    {{ include('viajero/_form.html.twig') }}

    <a href="{{ path('app_viajero_index') }}">back to list</a>
{% endblock %}

templates/viajero/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Viajero{% endblock %}

{% block body %}
    <h1>Viajero</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ viajero.id }}</td>
            </tr>
            <tr>
                <th>Cedula</th>
                <td>{{ viajero.cedula }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ viajero.nombre }}</td>
            </tr>
            <tr>
                <th>Fecha_nacimiento</th>
                <td>{{ viajero.fechaNacimiento ? viajero.fechaNacimiento|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ viajero.telefono }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_viajero_index') }}">back to list</a>

    <a href="{{ path('app_viajero_edit', {'id': viajero.id}) }}">edit</a>

    {{ include('viajero/_delete_form.html.twig') }}
{% endblock %}